-- 1. Ensure the "Assembly" category exists
INSERT INTO categories (name, slug) 
VALUES ('Assembly', 'assembly') 
ON CONFLICT (slug) DO NOTHING;

-- 2. Support multiple categories per recipe
-- We create a junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS recipe_categories (
  recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  category_id bigint REFERENCES categories(id) ON DELETE CASCADE,
  is_primary boolean DEFAULT false,
  PRIMARY KEY (recipe_id, category_id)
);

ALTER TABLE recipe_categories ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false;

-- Migrate existing single categories to the new table as primary categories
-- (Avoiding duplicates if run multiple times)
INSERT INTO recipe_categories (recipe_id, category_id, is_primary)
SELECT id, category_id, true
FROM recipes
WHERE category_id IS NOT NULL
ON CONFLICT (recipe_id, category_id) DO NOTHING;

-- 3. Recipes Involved (Linked Recipes)
-- Create a junction table to link parent assemblies to child recipes
CREATE TABLE IF NOT EXISTS recipe_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  child_recipe_id uuid REFERENCES recipes(id) ON DELETE CASCADE,
  sort_order integer DEFAULT 0,
  notes text, -- Optional note like "For the sauce"
  UNIQUE(parent_recipe_id, child_recipe_id)
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS recipe_links_parent_idx ON recipe_links(parent_recipe_id);

-- 4. Enable RLS and add policies
ALTER TABLE recipe_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipe_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Recipe categories are public." ON recipe_categories;
CREATE POLICY "Recipe categories are public." ON recipe_categories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert recipe categories for own recipes." ON recipe_categories;
CREATE POLICY "Users can insert recipe categories for own recipes." ON recipe_categories FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM recipes WHERE id = recipe_categories.recipe_id AND author_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can delete recipe categories for own recipes." ON recipe_categories;
CREATE POLICY "Users can delete recipe categories for own recipes." ON recipe_categories FOR DELETE USING (
  EXISTS (SELECT 1 FROM recipes WHERE id = recipe_categories.recipe_id AND author_id = auth.uid())
);

DROP POLICY IF EXISTS "Recipe links are public." ON recipe_links;
CREATE POLICY "Recipe links are public." ON recipe_links FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert recipe links for own recipes." ON recipe_links;
CREATE POLICY "Users can insert recipe links for own recipes." ON recipe_links FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM recipes WHERE id = recipe_links.parent_recipe_id AND author_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can update recipe links for own recipes." ON recipe_links;
CREATE POLICY "Users can update recipe links for own recipes." ON recipe_links FOR UPDATE USING (
  EXISTS (SELECT 1 FROM recipes WHERE id = recipe_links.parent_recipe_id AND author_id = auth.uid())
);

DROP POLICY IF EXISTS "Users can delete recipe links for own recipes." ON recipe_links;
CREATE POLICY "Users can delete recipe links for own recipes." ON recipe_links FOR DELETE USING (
  EXISTS (SELECT 1 FROM recipes WHERE id = recipe_links.parent_recipe_id AND author_id = auth.uid())
);
