-- Create table for daily planner notes
create table daily_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  date date not null,
  note text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date)
);

-- RLS Policies
alter table daily_notes enable row level security;

create policy "Users can see their own notes." on daily_notes for select using (auth.uid() = user_id);
create policy "Users can insert their own notes." on daily_notes for insert with check (auth.uid() = user_id);
create policy "Users can update their own notes." on daily_notes for update using (auth.uid() = user_id);
create policy "Users can delete their own notes." on daily_notes for delete using (auth.uid() = user_id);

-- Index
create index daily_notes_user_date_idx on daily_notes(user_id, date);
