-- Migration v4: Performance Indexes & Keywords Autocomplete Feature

-- 1. Create indices for performance optimizations
CREATE INDEX IF NOT EXISTS reviews_recipe_id_idx ON reviews(recipe_id);
CREATE INDEX IF NOT EXISTS reviews_user_id_idx ON reviews(user_id);
CREATE INDEX IF NOT EXISTS recipe_categories_recipe_id_category_id_idx ON recipe_categories(recipe_id, category_id);

-- 2. Create keywords table
CREATE TABLE IF NOT EXISTS keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

-- 3. Create recipe_keywords join table
CREATE TABLE IF NOT EXISTS recipe_keywords (
    recipe_id UUID REFERENCES recipes(id) ON DELETE CASCADE,
    keyword_id BIGINT REFERENCES keywords(id) ON DELETE CASCADE,
    PRIMARY KEY (recipe_id, keyword_id)
);

CREATE INDEX IF NOT EXISTS recipe_keywords_recipe_id_idx ON recipe_keywords(recipe_id);

-- 4. Enable Row Level Security (RLS) on new tables
ALTER TABLE keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipe_keywords ENABLE ROW LEVEL SECURITY;

-- 5. Set up RLS Policies
-- Keywords Policies
DROP POLICY IF EXISTS "Keywords are public." ON keywords;
CREATE POLICY "Keywords are public." ON keywords FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can insert keywords." ON keywords;
CREATE POLICY "Authenticated users can insert keywords." ON keywords FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Recipe-Keywords Join Policies
DROP POLICY IF EXISTS "Recipe keywords are public." ON recipe_keywords;
CREATE POLICY "Recipe keywords are public." ON recipe_keywords FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can manage recipe keywords." ON recipe_keywords;
CREATE POLICY "Users can manage recipe keywords." ON recipe_keywords FOR ALL USING (
    EXISTS (
        SELECT 1 FROM recipes 
        WHERE id = recipe_keywords.recipe_id 
        AND (author_id = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
    )
);

-- 6. Pre-seed with some common keywords to bootstrap the autocomplete list
INSERT INTO keywords (name) VALUES
('Gluten-Free'),
('Vegan'),
('Vegetarian'),
('Dairy-Free'),
('Low-Carb'),
('Keto'),
('Quick & Easy'),
('Dinner'),
('Breakfast'),
('Dessert'),
('Meal Prep'),
('Spicy'),
('Baking'),
('Seafood'),
('Comfort Food'),
('Healthy'),
('Lebanese'),
('Italian'),
('Mexican'),
('Asian')
ON CONFLICT (name) DO NOTHING;
